/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../common";

export declare namespace GoldenSchema {
  export type EntityTypeStruct = {
    entityTypeID: BytesLike;
    latestCID: BytesLike;
  };

  export type EntityTypeStructOutput = [string, string] & {
    entityTypeID: string;
    latestCID: string;
  };

  export type PredicateStruct = {
    predicateID: BytesLike;
    latestCID: BytesLike;
  };

  export type PredicateStructOutput = [string, string] & {
    predicateID: string;
    latestCID: string;
  };
}

export interface GoldenSchemaInterface extends utils.Interface {
  functions: {
    "addEntityType(bytes16,bytes32)": FunctionFragment;
    "addPredicate(bytes16,bytes32)": FunctionFragment;
    "entityTypeIDToLatestCID(bytes16)": FunctionFragment;
    "entityTypes()": FunctionFragment;
    "initialize((bytes16,bytes32)[],(bytes16,bytes32)[])": FunctionFragment;
    "owner()": FunctionFragment;
    "predicateIDToLatestCID(bytes16)": FunctionFragment;
    "predicates()": FunctionFragment;
    "removeEntityType(bytes16)": FunctionFragment;
    "removePredicate(bytes16)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "updateEntityType(bytes16,bytes32)": FunctionFragment;
    "updatePredicate(bytes16,bytes32)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "addEntityType"
      | "addPredicate"
      | "entityTypeIDToLatestCID"
      | "entityTypes"
      | "initialize"
      | "owner"
      | "predicateIDToLatestCID"
      | "predicates"
      | "removeEntityType"
      | "removePredicate"
      | "renounceOwnership"
      | "transferOwnership"
      | "updateEntityType"
      | "updatePredicate"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addEntityType",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "addPredicate",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "entityTypeIDToLatestCID",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "entityTypes",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [GoldenSchema.PredicateStruct[], GoldenSchema.EntityTypeStruct[]]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "predicateIDToLatestCID",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "predicates",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "removeEntityType",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removePredicate",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateEntityType",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updatePredicate",
    values: [BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "addEntityType",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addPredicate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "entityTypeIDToLatestCID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "entityTypes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "predicateIDToLatestCID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "predicates", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeEntityType",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removePredicate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateEntityType",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updatePredicate",
    data: BytesLike
  ): Result;

  events: {
    "EntityTypeAdded(bytes16,bytes32)": EventFragment;
    "EntityTypeRemoved(bytes16,bytes32)": EventFragment;
    "EntityTypeUpdated(bytes16,bytes32)": EventFragment;
    "Initialized(uint8)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "PredicateAdded(bytes16,bytes32)": EventFragment;
    "PredicateRemoved(bytes16,bytes32)": EventFragment;
    "PredicateUpdated(bytes16,bytes32)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "EntityTypeAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "EntityTypeRemoved"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "EntityTypeUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Initialized"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PredicateAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PredicateRemoved"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PredicateUpdated"): EventFragment;
}

export interface EntityTypeAddedEventObject {
  entityTypeID: string;
  latestCID: string;
}
export type EntityTypeAddedEvent = TypedEvent<
  [string, string],
  EntityTypeAddedEventObject
>;

export type EntityTypeAddedEventFilter = TypedEventFilter<EntityTypeAddedEvent>;

export interface EntityTypeRemovedEventObject {
  entityTypeID: string;
  latestCID: string;
}
export type EntityTypeRemovedEvent = TypedEvent<
  [string, string],
  EntityTypeRemovedEventObject
>;

export type EntityTypeRemovedEventFilter =
  TypedEventFilter<EntityTypeRemovedEvent>;

export interface EntityTypeUpdatedEventObject {
  entityTypeID: string;
  latestCID: string;
}
export type EntityTypeUpdatedEvent = TypedEvent<
  [string, string],
  EntityTypeUpdatedEventObject
>;

export type EntityTypeUpdatedEventFilter =
  TypedEventFilter<EntityTypeUpdatedEvent>;

export interface InitializedEventObject {
  version: number;
}
export type InitializedEvent = TypedEvent<[number], InitializedEventObject>;

export type InitializedEventFilter = TypedEventFilter<InitializedEvent>;

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface PredicateAddedEventObject {
  predicateID: string;
  latestCID: string;
}
export type PredicateAddedEvent = TypedEvent<
  [string, string],
  PredicateAddedEventObject
>;

export type PredicateAddedEventFilter = TypedEventFilter<PredicateAddedEvent>;

export interface PredicateRemovedEventObject {
  predicateID: string;
  latestCID: string;
}
export type PredicateRemovedEvent = TypedEvent<
  [string, string],
  PredicateRemovedEventObject
>;

export type PredicateRemovedEventFilter =
  TypedEventFilter<PredicateRemovedEvent>;

export interface PredicateUpdatedEventObject {
  predicateID: string;
  latestCID: string;
}
export type PredicateUpdatedEvent = TypedEvent<
  [string, string],
  PredicateUpdatedEventObject
>;

export type PredicateUpdatedEventFilter =
  TypedEventFilter<PredicateUpdatedEvent>;

export interface GoldenSchema extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: GoldenSchemaInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addEntityType(
      entityTypeID: BytesLike,
      entityTypeCID: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    addPredicate(
      predicateID: BytesLike,
      predicateCID: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    entityTypeIDToLatestCID(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    entityTypes(
      overrides?: CallOverrides
    ): Promise<[GoldenSchema.EntityTypeStructOutput[]]>;

    initialize(
      initialPredicates: GoldenSchema.PredicateStruct[],
      initialEntityTypes: GoldenSchema.EntityTypeStruct[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    predicateIDToLatestCID(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    predicates(
      overrides?: CallOverrides
    ): Promise<[GoldenSchema.PredicateStructOutput[]]>;

    removeEntityType(
      entityTypeID: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    removePredicate(
      predicateID: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateEntityType(
      entityTypeID: BytesLike,
      entityTypeCID: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updatePredicate(
      predicateID: BytesLike,
      predicateCID: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  addEntityType(
    entityTypeID: BytesLike,
    entityTypeCID: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  addPredicate(
    predicateID: BytesLike,
    predicateCID: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  entityTypeIDToLatestCID(
    arg0: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  entityTypes(
    overrides?: CallOverrides
  ): Promise<GoldenSchema.EntityTypeStructOutput[]>;

  initialize(
    initialPredicates: GoldenSchema.PredicateStruct[],
    initialEntityTypes: GoldenSchema.EntityTypeStruct[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  owner(overrides?: CallOverrides): Promise<string>;

  predicateIDToLatestCID(
    arg0: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  predicates(
    overrides?: CallOverrides
  ): Promise<GoldenSchema.PredicateStructOutput[]>;

  removeEntityType(
    entityTypeID: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  removePredicate(
    predicateID: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateEntityType(
    entityTypeID: BytesLike,
    entityTypeCID: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updatePredicate(
    predicateID: BytesLike,
    predicateCID: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    addEntityType(
      entityTypeID: BytesLike,
      entityTypeCID: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    addPredicate(
      predicateID: BytesLike,
      predicateCID: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    entityTypeIDToLatestCID(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    entityTypes(
      overrides?: CallOverrides
    ): Promise<GoldenSchema.EntityTypeStructOutput[]>;

    initialize(
      initialPredicates: GoldenSchema.PredicateStruct[],
      initialEntityTypes: GoldenSchema.EntityTypeStruct[],
      overrides?: CallOverrides
    ): Promise<void>;

    owner(overrides?: CallOverrides): Promise<string>;

    predicateIDToLatestCID(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    predicates(
      overrides?: CallOverrides
    ): Promise<GoldenSchema.PredicateStructOutput[]>;

    removeEntityType(
      entityTypeID: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    removePredicate(
      predicateID: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    updateEntityType(
      entityTypeID: BytesLike,
      entityTypeCID: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    updatePredicate(
      predicateID: BytesLike,
      predicateCID: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "EntityTypeAdded(bytes16,bytes32)"(
      entityTypeID?: BytesLike | null,
      latestCID?: BytesLike | null
    ): EntityTypeAddedEventFilter;
    EntityTypeAdded(
      entityTypeID?: BytesLike | null,
      latestCID?: BytesLike | null
    ): EntityTypeAddedEventFilter;

    "EntityTypeRemoved(bytes16,bytes32)"(
      entityTypeID?: BytesLike | null,
      latestCID?: BytesLike | null
    ): EntityTypeRemovedEventFilter;
    EntityTypeRemoved(
      entityTypeID?: BytesLike | null,
      latestCID?: BytesLike | null
    ): EntityTypeRemovedEventFilter;

    "EntityTypeUpdated(bytes16,bytes32)"(
      entityTypeID?: BytesLike | null,
      latestCID?: BytesLike | null
    ): EntityTypeUpdatedEventFilter;
    EntityTypeUpdated(
      entityTypeID?: BytesLike | null,
      latestCID?: BytesLike | null
    ): EntityTypeUpdatedEventFilter;

    "Initialized(uint8)"(version?: null): InitializedEventFilter;
    Initialized(version?: null): InitializedEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;

    "PredicateAdded(bytes16,bytes32)"(
      predicateID?: BytesLike | null,
      latestCID?: BytesLike | null
    ): PredicateAddedEventFilter;
    PredicateAdded(
      predicateID?: BytesLike | null,
      latestCID?: BytesLike | null
    ): PredicateAddedEventFilter;

    "PredicateRemoved(bytes16,bytes32)"(
      predicateID?: BytesLike | null,
      latestCID?: BytesLike | null
    ): PredicateRemovedEventFilter;
    PredicateRemoved(
      predicateID?: BytesLike | null,
      latestCID?: BytesLike | null
    ): PredicateRemovedEventFilter;

    "PredicateUpdated(bytes16,bytes32)"(
      predicateID?: BytesLike | null,
      latestCID?: BytesLike | null
    ): PredicateUpdatedEventFilter;
    PredicateUpdated(
      predicateID?: BytesLike | null,
      latestCID?: BytesLike | null
    ): PredicateUpdatedEventFilter;
  };

  estimateGas: {
    addEntityType(
      entityTypeID: BytesLike,
      entityTypeCID: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    addPredicate(
      predicateID: BytesLike,
      predicateCID: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    entityTypeIDToLatestCID(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    entityTypes(overrides?: CallOverrides): Promise<BigNumber>;

    initialize(
      initialPredicates: GoldenSchema.PredicateStruct[],
      initialEntityTypes: GoldenSchema.EntityTypeStruct[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    predicateIDToLatestCID(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    predicates(overrides?: CallOverrides): Promise<BigNumber>;

    removeEntityType(
      entityTypeID: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    removePredicate(
      predicateID: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateEntityType(
      entityTypeID: BytesLike,
      entityTypeCID: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updatePredicate(
      predicateID: BytesLike,
      predicateCID: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addEntityType(
      entityTypeID: BytesLike,
      entityTypeCID: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    addPredicate(
      predicateID: BytesLike,
      predicateCID: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    entityTypeIDToLatestCID(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    entityTypes(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    initialize(
      initialPredicates: GoldenSchema.PredicateStruct[],
      initialEntityTypes: GoldenSchema.EntityTypeStruct[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    predicateIDToLatestCID(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    predicates(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    removeEntityType(
      entityTypeID: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    removePredicate(
      predicateID: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateEntityType(
      entityTypeID: BytesLike,
      entityTypeCID: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updatePredicate(
      predicateID: BytesLike,
      predicateCID: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
