/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as lockedStaking from "./locked-staking";
export type { lockedStaking };
import type * as nft from "./nft";
export type { nft };
export type { GoldenSchema } from "./GoldenSchema";
export type { GoldenSchemaGovernor } from "./GoldenSchemaGovernor";
export type { GoldenToken } from "./GoldenToken";
export type { IGoldenToken } from "./IGoldenToken";
export type { StakeableUpgradeable } from "./StakeableUpgradeable";
