/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { GoldenToken__factory } from "./GoldenToken__factory";
export { IGoldenToken__factory } from "./IGoldenToken__factory";
