/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { GoldenProtocol } from "./GoldenProtocol";
export type { GoldenProtocolQuestion } from "./GoldenProtocolQuestion";
