/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IReputation,
  IReputationInterface,
} from "../../../contracts/reputation/IReputation";

const _abi = [
  {
    inputs: [],
    name: "getMaxReputation",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_address",
        type: "address",
      },
    ],
    name: "getReputation",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_address",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
    ],
    name: "setReputation",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IReputation__factory {
  static readonly abi = _abi;
  static createInterface(): IReputationInterface {
    return new utils.Interface(_abi) as IReputationInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IReputation {
    return new Contract(address, _abi, signerOrProvider) as IReputation;
  }
}
