/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { GoldenStaking } from "./GoldenStaking";
export type { IGoldenStaking } from "./IGoldenStaking";
