name: Run Tests

concurrency:
  group: run-tests-${{ github.head_ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches: [master]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3

      - name: Set up dependencies
        env:
          YARN_ENABLE_COLORS: false
          YARN_ENABLE_PROGRESS_BARS: false
        run: |
          yarn

      - name: Run tests
        run: |
          set -ex
          yarn lint
          yarn types
          yarn test
          [ -z "$(git status --porcelain)" ]
  tenderly:
    if: ${{ github.event.label.name == 'tenderly' }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: |
          export NODE_ENV=development
          yarn install --frozen-lockfile

      - name: Setup environment variables
        env:
          TENDERLY_USER: ${{ secrets.TENDERLY_USER }}
          TENDERLY_PROJECT: ${{ secrets.TENDERLY_PROJECT }}
          TENDERLY_ACCESS_KEY: ${{ secrets.TENDERLY_ACCESS_KEY }}

      - name: Fork mainnet
        run: |
          yarn fork

      - name: Write output to .env
        run: |
          echo "TENDERLY_FORK_ID=${{ steps.tenderly.outputs.simulation_fork.id }}"