name: Upload Predicates to IPFS

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  upload-predicates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v24
      
      - name: Run this step only when GoldenSchemaPredicates.json changes
        env:
          INFURA_AUTH_TOKEN: ${{ secrets.INFURA_AUTH_TOKEN }}
        if: ${{ github.event_name == 'workflow_dispatch' || contains(steps.changed-files.outputs.modified_files, 'contracts/GoldenSchemaPredicates.json') }}
        run: |
          yarn
          npx ts-node ipfs/data/preloadPredicates.ts
    
      


      
