name: Vulnerability code scanning

on: [pull_request]

jobs:
  vulnerability-scanner-slither:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3

      - name: Set up dependencies
        run:
          yarn

      - name: Run Slither
        uses: crytic/slither-action@v0.1.1
        id: slither
