/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as stakingStorageSol from "./StakingStorage.sol";
export type { stakingStorageSol };
export type { IStake } from "./IStake";
export type { Staking } from "./Staking";
